//! Bakes `assets/font.ttf` into a bitmap font atlas at build time.
//!
//! Rasterising TrueType on a 222 MHz MIPS is not affordable, so the glyphs are
//! rendered here, on the host, into a single 8-bit alpha atlas the PSP uploads
//! as a texture and draws as quads.

use fontdue::{Font, FontSettings};
use std::fmt::Write as _;
use std::path::PathBuf;

/// Printable ASCII plus the arrows the on-screen hints use.
const FIRST_CHAR: u8 = 32;
const LAST_CHAR: u8 = 126;
/// Rendered size. Text is scaled on the PSP, so this only sets sharpness.
///
/// Tiny5 is a pixel font on a 5-unit grid and its capitals are 9/16 of the em,
/// so this size puts them on 25 pixels - an exact 5x of the design grid, where
/// every drawn pixel is a whole block rather than a blend of two.
const GLYPH_PX: f32 = 44.45;
/// Atlas is a power of two, as the GE expects for textures.
const ATLAS_W: usize = 512;
const ATLAS_H: usize = 256;

fn main() {
    println!("cargo:rerun-if-changed=assets/font.ttf");
    println!("cargo:rerun-if-changed=build.rs");

    let bytes = std::fs::read("assets/font.ttf").expect("assets/font.ttf missing");
    let font = Font::from_bytes(bytes.as_slice(), FontSettings::default()).expect("bad font");

    let mut atlas = vec![0u8; ATLAS_W * ATLAS_H];
    let mut glyphs = Vec::new();

    let (mut pen_x, mut pen_y, mut row_h) = (0usize, 0usize, 0usize);

    for code in FIRST_CHAR..=LAST_CHAR {
        let ch = code as char;
        let (metrics, bitmap) = font.rasterize(ch, GLYPH_PX);
        let (gw, gh) = (metrics.width, metrics.height);

        if pen_x + gw + 1 >= ATLAS_W {
            pen_x = 0;
            pen_y += row_h + 1;
            row_h = 0;
        }
        assert!(
            pen_y + gh < ATLAS_H,
            "font atlas too small for {GLYPH_PX}px glyphs"
        );

        for y in 0..gh {
            for x in 0..gw {
                atlas[(pen_y + y) * ATLAS_W + pen_x + x] = bitmap[y * gw + x];
            }
        }

        glyphs.push(GlyphEntry {
            u: pen_x as u16,
            v: pen_y as u16,
            w: gw as u16,
            h: gh as u16,
            // fontdue's ymin is the distance from the baseline to the glyph's
            // bottom; the renderer wants the top offset instead.
            top: (-(metrics.ymin as f32) - gh as f32) as i16,
            left: metrics.xmin as i16,
            advance: metrics.advance_width,
        });

        pen_x += gw + 1;
        row_h = row_h.max(gh);
    }

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    std::fs::write(out_dir.join("font_atlas.bin"), &atlas).unwrap();

    let mut table = String::new();
    writeln!(table, "// Generated by build.rs - do not edit.").unwrap();
    writeln!(table, "pub const ATLAS_W: usize = {ATLAS_W};").unwrap();
    writeln!(table, "pub const ATLAS_H: usize = {ATLAS_H};").unwrap();
    writeln!(table, "pub const GLYPH_PX: f32 = {GLYPH_PX:?};").unwrap();
    // The height of a capital. This, not the em, is what the eye reads and
    // what every text size in the game was tuned against, so the renderer
    // scales by it and a font swap leaves the layout where it was.
    let cap_px = font.rasterize('M', GLYPH_PX).0.height as f32;
    writeln!(table, "pub const CAP_PX: f32 = {cap_px:?};").unwrap();
    writeln!(table, "pub const FIRST_CHAR: u8 = {FIRST_CHAR};").unwrap();
    writeln!(table, "pub const LAST_CHAR: u8 = {LAST_CHAR};").unwrap();
    writeln!(
        table,
        "pub static GLYPHS: [Glyph; {}] = [",
        glyphs.len()
    )
    .unwrap();
    for g in &glyphs {
        writeln!(
            table,
            "    Glyph {{ u: {}, v: {}, w: {}, h: {}, top: {}, left: {}, advance: {:?} }},",
            g.u, g.v, g.w, g.h, g.top, g.left, g.advance
        )
        .unwrap();
    }
    writeln!(table, "];").unwrap();
    std::fs::write(out_dir.join("font_table.rs"), table).unwrap();
}

struct GlyphEntry {
    u: u16,
    v: u16,
    w: u16,
    h: u16,
    top: i16,
    left: i16,
    advance: f32,
}
